### ISSUE TITLE
CADdyTools not compatible with win 10 x64

### ISSUE THREAD

**Issue by gurikbal** [MarioRosi/CADdyTools#2]
![capture-20200311-153449](https://user-images.githubusercontent.com/36083297/76405298-ec1c6f80-63ad-11ea-9436-d6f2bd68fdb0.png)

**Comment by MarioRosi** [comment]
Hello gurikbal,

i test the plugin on my windows 10 x64 with 7.8.1 and 7.8.5  and it works?!
![CADdyTools](https://user-images.githubusercontent.com/44395810/77093584-721e6300-6a0b-11ea-8db3-1d9cbfcb7e90.jpg)

What can be the cause of you?
regards Mario

**Comment by gurikbal** [comment]
![WonderFox_Video_Recording_001_001](https://user-images.githubusercontent.com/36083297/77098311-2d5cf100-6a38-11ea-8c31-fe278c4c4225.gif)

**Comment by gurikbal** [comment]
related issue agenda https://github.com/gurikbal/Remove_dup_lines/issues/2

**Comment by MarioRosi** [comment]
Hi gurikbal,

i have new compile with files from "NppPlugin0.94.00.zip"

My NPP-debuginfo :
Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.720
Plugins : CADdyTools.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

Can your test the plain dll from attached zip please?

regards Mario
[CADdyTools.zip](https://github.com/MarioRosi/CADdyTools/files/4356478/CADdyTools.zip)

**Comment by gurikbal** [comment]
https://youtu.be/fLaZmb9iEXE

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.449
Plugins : mimeTools.dll NppConverter.dll NppExport.dll Remove Duplicate Lines.dll

**Comment by gurikbal** [comment]
you can check dll file what i accept on win 10

https://gitlab.com/dokutoku/rdmd-for-npp/-/issues/8

**Comment by MarioRosi** [comment]
... now i was able to reproduce the error.  The problem is follow:
- i install the Notepad++ on my computer with german language pack. With this run the plugin, without not.

Is no languagepack installt or only the english-languagepack, non exist the "C:\Users\xxxx\AppData\Roaming\Notepad++\nativeLang.xml". That i have no checked before read this file 8-()

... now it works

**Comment by gurikbal** [comment]
https://github.com/MarioRosi/CADdyTools/releases/tag/1.0.1.5

x86 and x64 dll now works for me
